import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Produtos",
    description: "Generated by create next app",
  };

  export default function ProductLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <>
          {children}
      </>
    );
  }
  